Models/FileinLesson.cs
namespace deha_exam_quanlykhoahoc.Models
{
    public class FileinLesson
    {
        public int Id { get; set; }
        public string? name { get; set; }

        public string? filePath { get; set; }
        public int LessonID { get; set; }
        public Lesson? Lesson { get; set; }
    }
}

Controllers/FileinLessonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using deha_exam_quanlykhoahoc;
using deha_exam_quanlykhoahoc.Models;
using deha_exam_quanlykhoahoc.Services;
using Microsoft.AspNetCore.StaticFiles;
using deha_exam_quanlykhoahoc.ViewModels;

namespace deha_exam_quanlykhoahoc.Controllers
{
    public class FileinLessonsController : Controller
    {
        private readonly MyDBContext _context;
        private readonly IFileinLessonService _fileinLessonService;
        private const string USER_CONTENT_FOLDER_NAME = "user-content";
        private readonly IWebHostEnvironment _hostingEnvironment;

        public FileinLessonsController(MyDBContext context, IFileinLessonService fileinLessonService, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _fileinLessonService = fileinLessonService;
            _hostingEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Download(int fileId)
        {
            var myfile = await _fileinLessonService.GetById(fileId);
            if (myfile == null)
                return NotFound();
            else
            {
                var webRootPath = _hostingEnvironment.WebRootPath;
          //      var filePath = Path.Combine(webRootPath, myfile.filePath);
                var filePath = Path.GetFullPath(Path.Combine(webRootPath, myfile.filePath.TrimStart('/')));
                if (!System.IO.File.Exists(filePath))
                {
                    return NotFound();
                }
                // Infer content type based on file extension
                var contentTypeProvider = new FileExtensionContentTypeProvider();
                if (!contentTypeProvider.TryGetContentType(myfile.name, out var contentType))
                {
                    contentType = "application/octet-stream"; // Default content type if not found
                }
                return PhysicalFile(filePath, contentType, myfile.name);
            }
        }
        // GET: FileinLessons
        public async Task<IActionResult> Index()
        {
            var myDBContext = _context.FileinLesson.Include(f => f.Lesson);
            return View(await myDBContext.ToListAsync());
        }

        // GET: FileinLessons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.FileinLesson == null)
            {
                return NotFound();
            }

            var fileinLesson = await _context.FileinLesson
                .Include(f => f.Lesson)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fileinLesson == null)
            {
                return NotFound();
            }

            return View(fileinLesson);
        }

        // GET: FileinLessons/Create
        public IActionResult Create()
        {
            ViewData["LessonID"] = new SelectList(_context.Lesson, "Id", "Id");
            return View();
        }

        // POST: FileinLessons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,name,filePath,LessonID")] FileinLesson fileinLesson)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fileinLesson);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LessonID"] = new SelectList(_context.Lesson, "Id", "Id", fileinLesson.LessonID);
            return View(fileinLesson);
        }

        // GET: FileinLessons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var fileinLesson = await _fileinLessonService.GetById(id);
            if (fileinLesson == null)
            {
                return NotFound();
            }
           // ViewData["LessonID"] = new SelectList(_context.Lesson, "Id", "Id", fileinLesson.LessonID);
            return View(fileinLesson);
        }

        // POST: FileinLessons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, FileInLessonModel fileInLessonModel)
        {
            if (id != fileInLessonModel.Id)
            {
                return NotFound();
            }
            var fileinLesson = await _fileinLessonService.GetById(id);
            var result = await _fileinLessonService.Update(fileInLessonModel);
            TempData["Message"] = result.message;
            return RedirectToAction("Edit", "Lessons", new { id = fileinLesson.LessonID });
        }

        // GET: FileinLessons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var fileinLesson = await _fileinLessonService.GetById(id);
            if (fileinLesson == null)
            {
                return NotFound();
            }

            return View(fileinLesson);
        }

        // POST: FileinLessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fileinLesson = await _fileinLessonService.GetById(id);
            var result = await _fileinLessonService.Delete(id);
            TempData["Message"] = result.message;
            return RedirectToAction("Edit", "Lessons", new { id = fileinLesson.LessonID });
        }

        private bool FileinLessonExists(int id)
        {
          return (_context.FileinLesson?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/FileinLessons/Create.cshtml
@model deha_exam_quanlykhoahoc.Models.FileinLesson

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FileinLesson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="filePath" class="control-label"></label>
                <input asp-for="filePath" class="form-control" />
                <span asp-validation-for="filePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LessonID" class="control-label"></label>
                <select asp-for="LessonID" class ="form-control" asp-items="ViewBag.LessonID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FileinLessons/Delete.cshtml
@model deha_exam_quanlykhoahoc.ViewModels.FileInLessonModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FileinLesson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.filePath)
        </dt>
        <dd class = "col-sm-10">
            <a asp-action="Download" asp-controller="FileinLessons" asp-route-fileId="@Model.Id">@Model.name</a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lesson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lesson.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Edit" asp-controller="Lessons" asp-route-id="@Model.LessonID">Back to List</a>
    </form>
</div>

Views/FileinLessons/Details.cshtml
@model deha_exam_quanlykhoahoc.Models.FileinLesson

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FileinLesson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.filePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.filePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lesson)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lesson.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/FileinLessons/Edit.cshtml
@model deha_exam_quanlykhoahoc.ViewModels.FileInLessonModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FileinLesson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group" style="display:none;">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" value="@Model.name" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div> 
            <div class="form-group" style="display:none;">
                <label asp-for="filePath" class="control-label"></label>
                <input asp-for="filePath" class="form-control" value="@Model.filePath" />
                <span asp-validation-for="filePath" class="text-danger"></span>
            </div>
            <div class="form-group" style="display:none;">
                <label asp-for="LessonID" class="control-label"></label>
                <input asp-for="LessonID" class="form-control" value="@Model.LessonID" />
                <span asp-validation-for="LessonID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Current File:</label>
                <a asp-action="Download" asp-controller="FileinLessons" asp-route-fileId="@Model.Id">@Model.name</a>
            </div>
            <div class="form-group">
                <label asp-for="file" class="control-label"></label>
                <input asp-for="file" type="file" required="required" />
                <!--   <select asp-for="ClassID" class ="form-control" asp-items="ViewBag.ClassID"></select> -->
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-controller="Lessons" asp-route-id="@Model.LessonID">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FileinLessons/Index.cshtml
@model IEnumerable<deha_exam_quanlykhoahoc.Models.FileinLesson>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.filePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lesson)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.filePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lesson.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>